version: '3'

services:
  redis:
    image: redis:5.0.9

  web:
    image: python-test:1.2
    environment:
        - ENVIRONMENT=DEV
        - HOST=localhost
        - PORT=8000
        - REDIS_HOST=redis.local
        - REDIS_PORT=6379
        - REDIS_DB=0
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - "redis:redis.local"